#!/bin/bash
#SET VARS REGARDING THE PATH TO THE NTFS PARTITION
ntfs_path=`find /storage -type d -iname 'system volume information' 2> /dev/null | head -1`
ntfs_path=${ntfs_path%/*}
uuid=${ntfs_path#*/storage/}
label=`logcat -d | grep $uuid | grep LABEL`
label=${label#*LABEL='"'}
label=${label%'"' T*}
ntfs_path+="/RemixOS-Logs"
#PATH TO SAVE FILES REMIX FRIENDLY
remix_path="/sdcard/RemixOS-Logs"
#SET VARS FOR LOGFILE NAMING
model=`getprop ro.product.model`
version=`getprop ro.build.remixos.version`
system_arch=`getprop ro.product.cpu.abi`
logcat="logcat_${model}_${version}_${system_arch}_$(date +%F_%R).txt"
dmesg="dmesg_${model}_${version}_${system_arch}_$(date +%F_%R).txt"
lspci="lspci_${model}_${version}_${system_arch}_$(date +%F_%R).txt"
lsusb="lsusb_${model}_${version}_${system_arch}_$(date +%F_%R).txt"
cpuinfo="cpuinfo_${model}_${version}_${system_arch}_$(date +%F_%R).txt"
#OUTPUT TEXT FORMATTING
echo
echo "Dumping log files, please wait..."
#CREATE A FOLDERS FOR THE LOGS (X/RemixOS-Logs)
mkdir -p $ntfs_path && mkdir -p $remix_path
#DUMP THE LOGS TO $ntfs_path AND COPY THEM TO $remix_path
dmesg >  $ntfs_path/$dmesg && lspci > /$ntfs_path/$lspci && logcat -d > /$ntfs_path/$logcat && lsusb > $ntfs_path/$lsusb && cat /proc/cpuinfo > /$ntfs_path/$cpuinfo
cp $ntfs_path/$dmesg $remix_path && cp $ntfs_path/$lspci $remix_path && cp $ntfs_path/$logcat $remix_path && cp $ntfs_path/$lsusb $remix_path && cp $ntfs_path/$cpuinfo $remix_path

echo "Dump complete"
echo 
echo "The logs were saved to 2 locations:"

echo "1. Windows friendly -  $label:\RemixOS-Logs folder.  The $label is the NTFS partition label (name)."
echo "2. Remix OS friendly - /sdcard/RemixOS-Logs folder"  
echo
echo "You can attach those logs to your GitHub issue. That's all :)"
